In [16]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/cleaned/creator_cleaned.csv"
)

df.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,5,7,34,4327,6230,0.0385,899,100,7,medium
1,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,2,1,22,1639,2616,0.0531,758,115,8,high
2,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,0,7,0,2877,3171,0.0309,402,115,7,medium
3,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,8,5,21,5350,8503,0.0221,155,112,9,low
4,IG0000006,7,brand,3551,carousel,Photography,Reels Feed,1,2025-05-06 08:00:00,2025-05-06,...,3,4,23,2668,3472,0.0516,904,111,5,high

In [17]:
print(df.shape)

print(df.info())

print(df.isnull().sum())

(23144, 23)
<class 'pandas.DataFrame'>
RangeIndex: 23144 entries, 0 to 23143
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   post_id                   23144 non-null  str
 1   account_id                23144 non-null  int64
 2   account_type              23144 non-null  str
 3   follower_count            23144 non-null  int64
 4   media_type                23144 non-null  str
 5   content_category          23144 non-null  str
 6   traffic_source            23144 non-null  str
 7   has_call_to_action        23144 non-null  int64
 8   post_datetime             23144 non-null  str
 9   post_date                 23144 non-null  str
 10  post_hour                 23144 non-null  int64
 11  day_of_week               23144 non-null  str
 12  likes                     23144 non-null  int64
 13  comments                  23144 non-null  int64
 14  shares                    23144 non-null  int64
 15  saves                     23144 non-null  int64
 16  reach                     23144 non-null  int64
 17  impressions               23144 non-null  int64
 18  engagement_rate           23144 non-null  float64
 19  followers_gained          23144 non-null  int64
 20  caption_length            23144 non-null  int64
 21  hashtags_count            23144 non-null  int64
 22  performance_bucket_label  23144 non-null  str
dtypes: float64(1), int64(13), str(9)
memory usage: 4.1 MB
None
post_id                     0
account_id                  0
account_type                0
follower_count              0
media_type                  0
content_category            0
traffic_source              0
has_call_to_action          0
post_datetime               0
post_date                   0
post_hour                   0
day_of_week                 0
likes                       0
comments                    0
shares                      0
saves                       0
reach                       0
impressions                 0
engagement_rate             0
followers_gained            0
caption_length              0
hashtags_count              0
performance_bucket_label    0
dtype: int64

In [18]:
df["post_date"] = pd.to_datetime(
    df["post_date"]
)

In [20]:
df["is_weekend"] = df["day_of_week"].isin(
    ["Saturday", "Sunday"]
).astype(int)
df["post_date"].dtype

dtype('<M8[us]')

In [21]:
df["year"] = df["post_date"].dt.year

In [22]:
df["month"] = df["post_date"].dt.month

In [23]:
df["month_name"] = (
    df["post_date"]
    .dt.month_name()
)

In [24]:
df["quarter"] = (
    df["post_date"]
    .dt.quarter
)

In [25]:
df["week"] = (
    df["post_date"]
    .dt.isocalendar()
    .week
)

In [26]:
df["is_weekend"] = (
    df["day_of_week"]
    .isin(
        ["Saturday", "Sunday"]
    )
    .astype(int)
)

In [27]:
def get_time_slot(hour):

    if 5 <= hour < 12:
        return "Morning"

    elif 12 <= hour < 17:
        return "Afternoon"

    elif 17 <= hour < 21:
        return "Evening"

    else:
        return "Night"

In [29]:
print(df.columns.tolist())

['post_id', 'account_id', 'account_type', 'follower_count', 'media_type', 'content_category', 'traffic_source', 'has_call_to_action', 'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes', 'comments', 'shares', 'saves', 'reach', 'impressions', 'engagement_rate', 'followers_gained', 'caption_length', 'hashtags_count', 'performance_bucket_label', 'is_weekend', 'year', 'month', 'month_name', 'quarter', 'week']

In [30]:
def get_time_slot(hour):

    if 5 <= hour < 12:
        return "Morning"

    elif 12 <= hour < 17:
        return "Afternoon"

    elif 17 <= hour < 21:
        return "Evening"

    else:
        return "Night"

df["time_slot"] = df["post_hour"].apply(get_time_slot)

In [31]:
print(df[["post_hour", "time_slot"]].head())

   post_hour  time_slot
0          6    Morning
1         16  Afternoon
2          3      Night
3          9    Morning
4          8    Morning

In [32]:
df[
[
"post_date",
"year",
"month",
"month_name",
"quarter",
"week",
"is_weekend",
"time_slot"
]
].head()

   post_date  year  month month_name  quarter  week  is_weekend  time_slot
0 2024-11-30  2024     11   November        4    48           1    Morning
1 2025-09-11  2025      9  September        3    37           0  Afternoon
2 2025-09-18  2025      9  September        3    38           0      Night
3 2025-03-21  2025      3      March        1    12           0    Morning
4 2025-05-06  2025      5        May        2    19           0    Morning

In [34]:
df.to_csv(
    "../data/processed/creator_preprocessed.csv",
    index=False
)